### ISSUE TITLE
having trouble compiling the project

### ISSUE THREAD

**Issue by hoebat** [hudsonb/kubed#10]
I'm getting this error when building the project

```
$ gradle
--------
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/chris/Development/buffer/kubed/kubed-contour/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':kubed-contour'.
> Could not find method sourcesJar() for arguments [build_b808absl75l1m7uhb220r46ft$_run_closure1$_closure6$_closure7$_closure8@b8b1f9d] on object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by hudsonb** [comment]
I just tested the build and was able to compile w/o issue using the gradle wrapper `gradlew`.  Did you use the gradle wrapper or your local gradle install? If you used your own local install, what version of gradle are you running?

**Comment by hoebat** [comment]
ah awesome. I used the local gradle install from homebrew. 

`gradlew` works great.

**Comment by hoebat** [comment]
I have gradle 5.0 installed. That was what was causing the issue.

**Comment by hudsonb** [comment]
I'll look into getting it to work under gradle 5 and get the wrapper updated.
