### ISSUE TITLE
Issues executing the project

### ISSUE THREAD

**Issue by dprutean** [hudsonb/kubed#11]
Hello,
I find the project interesting. I don't have Kotlin experience. I did git pull and tried to open the project in Intelij, it was complaining that JavaFx is missing. 
I added in kubed-demos build.gradle this:
	compile "org.openjfx:javafx-base:13:win" // ALL THIS ARE JAVAFX LIBRARIES
	compile "org.openjfx:javafx-graphics:13:win"
	compile "org.openjfx:javafx-controls:13:win"
	compile "org.openjfx:javafx-web:13:win"
	compile "org.openjfx:javafx-swing:13:win"
	compile "org.openjfx:javafx-media:13:win"
	compile 'no.tornado:tornadofx:1.7.15'

But then still the error in the image are shown. What i did wrong ? 

![image](https://user-images.githubusercontent.com/4970910/68058249-cd6be500-fcf8-11e9-909f-2271debbaec4.png)

**Comment by hudsonb** [comment]
kubed was originally targeting Java 8 so JavaFX was included. I'll get it updated for 13.

**Comment by hudsonb** [comment]
Issues should now be fixed, and I was able to execute the `SymbolDemo.kt` without issue.
